// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeREKyInfjUbsvPyzjGZXsLIj00n0Zko0',
    appId: '1:1039139293103:web:361de4e375ebfbd90f115a',
    messagingSenderId: '1039139293103',
    projectId: 'mwirigi-farm',
    authDomain: 'mwirigi-farm.firebaseapp.com',
    storageBucket: 'mwirigi-farm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBJlp9OnV_Igy5Peo-1f4AQ7ul9KcybI',
    appId: '1:1039139293103:android:4baf0af1bfd60ba10f115a',
    messagingSenderId: '1039139293103',
    projectId: 'mwirigi-farm',
    storageBucket: 'mwirigi-farm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBDJ7Lx2Kfc6hFcjgzjvo6Byj5CqWBs4A',
    appId: '1:1039139293103:ios:ff3ea9700c78c5bf0f115a',
    messagingSenderId: '1039139293103',
    projectId: 'mwirigi-farm',
    storageBucket: 'mwirigi-farm.firebasestorage.app',
    iosClientId: '1039139293103-ulci7npl6uqas2ovq9n1n2tahnseo0qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBDJ7Lx2Kfc6hFcjgzjvo6Byj5CqWBs4A',
    appId: '1:1039139293103:ios:ff3ea9700c78c5bf0f115a',
    messagingSenderId: '1039139293103',
    projectId: 'mwirigi-farm',
    storageBucket: 'mwirigi-farm.firebasestorage.app',
    iosClientId: '1039139293103-ulci7npl6uqas2ovq9n1n2tahnseo0qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeREKyInfjUbsvPyzjGZXsLIj00n0Zko0',
    appId: '1:1039139293103:web:ecde249ab2947ee10f115a',
    messagingSenderId: '1039139293103',
    projectId: 'mwirigi-farm',
    authDomain: 'mwirigi-farm.firebaseapp.com',
    storageBucket: 'mwirigi-farm.firebasestorage.app',
  );
}
